### ISSUE TITLE
Unbond liquidity button not showing

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifchain-ui#600]
unbonding button sometimes doesn’t appear. This is most probably connected to prior Add Liquidity action. After this is done, manual UI refresh needs to be done in order for Unbond Liquidity button to be shown

**Comment by tien** [comment]
Fixed by #594

**Comment by pgoos** [comment]
just needs to be verified on devenet/staging and then merged to master? I would keep it open until then, ok?

**Comment by tien** [comment]
Yes that make sense :D

**Comment by alanrsoares** [comment]
this fix has been deployed

**Comment by bksifchain** [comment]
@pgoos @sheokapr  - pls verify the fix is working in devnet. Thanks!

**Comment by sheokapr** [comment]
Production:
I just tried Unbond request in production, unbond timer appeared as soon as the unbond request txn goes through, then disappeared for a few secs (abt 10 secs) and appeared again (seems to be showing fine after first few secs when it disappeared). I can see below POST request failures in console.

DevNet:
In devnet, unbond timer looks fine.

**Comment by bksifchain** [comment]
@tien @sheokapr  - is this resolved with 2.5.9 release?

**Comment by pgoos** [comment]
@bksifchain looks like this is still not fixed on production.
Initial liquidity add to a pool should result in the button shown immediately after add liquidity completes which is not the case.

**Comment by bksifchain** [comment]
Closing this issue for now as there is no further FE are needed at this time. The Unbond CTA displays unless there is an error returned from sifnode
